version: '3.7'

services:

  configuration:
    build:
      context: .
      dockerfile: Dockerfile
      target: configuration
    container_name: configuration
    restart: always
    networks:
      - foodpuppy

  eureka:
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka
    container_name: eureka
    depends_on:
      - configuration
    environment:
      CONFIGURATION: configuration
    restart: always
    networks:
      - foodpuppy

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    environment:
      EUREKA_HOST: eureka
      CONFIGURATION: configuration
    restart: always
    networks:
      - foodpuppy

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user
    container_name: user
    depends_on:
      - eureka
    environment:
      SPRING_DATASOURCE_URL:
      EUREKA_HOST: eureka
      CONFIGURATION: configuration
    restart: always
    networks:
      - foodpuppy

  restaurant_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: restaurant
    container_name: restaurant
    depends_on:
      - eureka
    environment:
      SPRING_DATASOURCE_URL:
      EUREKA_HOST: eureka
      CONFIGURATION: configuration
    restart: always
    networks:
      - foodpuppy

networks:
  foodpuppy: