version: '3.7'

services:

  food_db:
    image: "mongo:latest"
    container_name: food_puppy_food_db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - foodpuppy

  eureka_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka_server
    container_name: food_puppy_eureka_server
    ports:
      - "8761:8761"
    depends_on:
      - food_db
    restart: always
    networks:
      - foodpuppy

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user_service
    container_name: food_puppy_user_service
    ports:
      - "8081:8081"
    depends_on:
      - food_db
      - eureka_server
    environment:
      SPRING_DATASOURCE_URL: mongodb://food_db:27017/food-puppy-user-service
      EUREKA_HOST: eureka_server
    restart: always
    networks:
      - foodpuppy

  restaurant_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: restaurant_service
    container_name: food_puppy_restaurant_service
    ports:
      - "8082:8082"
    depends_on:
      - food_db
      - eureka_server
    environment:
      SPRING_DATASOURCE_URL: mongodb://food_db:27017/food-puppy-restaurant-service
      EUREKA_HOST: eureka_server
    restart: always
    networks:
      - foodpuppy

networks:
  foodpuppy: