version: '3.7'

services:

  database:
    image: "mongo:latest"
    restart: always
    container_name: database
    networks:
      - foodgrid

  services:
    build:
      context: .
      dockerfile: Dockerfile
      target: services
    container_name: services
    depends_on:
      - database
    restart: always
    networks:
      - foodgrid
    ports:
      - "8888:8888"

networks:
  foodgrid: