version: '3.7'

services:

  user_db:
    image: "mongo:latest"
    container_name: food_puppy_user_db
    restart: always
    ports:
      - 27017:27017

  restaurant_db:
    image: "mongo:latest"
    container_name: food_puppy_restaurant_db
    restart: always
    ports:
      - 27018:27017

  eureka_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka_server
    container_name: food_puppy_eureka_server
    ports:
      - "8761:8761"
    depends_on:
      - user_db
      - restaurant_db
    restart: always

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user_service
    container_name: food_puppy_user_service
    ports:
      - "8081:8081"
    depends_on:
      - user_db
      - restaurant_db
    environment:
      SPRING_DATASOURCE_URL: mongodb://user_db:27017/food-puppy-user-service
      EUREKA_HOST: eureka_server
    restart: always

  restaurant_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: restaurant_service
    container_name: food_puppy_restaurant_service
    ports:
      - "8082:8082"
    depends_on:
      - user_db
      - restaurant_db
    environment:
      SPRING_DATASOURCE_URL: mongodb://restaurant_db:27018/food-puppy-restaurant-service
      EUREKA_HOST: eureka_server
    restart: always
