version: '3.7'

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FoodPuppy
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: mongodb://db:27017/mod-course
    restart: always

  db:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017