version: '3.7'

services:

  eureka:
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka
    container_name: eureka
    ports:
      - "8761:8761"
    restart: always
    networks:
      - foodpuppy

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    environment:
      EUREKA_HOST: eureka
    restart: always
    networks:
      - foodpuppy

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user
    container_name: user
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    environment:
      SPRING_DATASOURCE_URL:
      EUREKA_HOST: eureka
    restart: always
    networks:
      - foodpuppy

  restaurant_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: restaurant
    container_name: restaurant
    ports:
      - "8082:8082"
    depends_on:
      - eureka
    environment:
      SPRING_DATASOURCE_URL:
      EUREKA_HOST: eureka
    restart: always
    networks:
      - foodpuppy

networks:
  foodpuppy: