version: '3.7'

services:

  eureka:
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka
    container_name: eureka
    ports:
      - "8761:8761"
    expose:
      - "8761"
    restart: always

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    environment:
      EUREKA_HOST: eureka
    restart: always

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user
    container_name: user
    expose:
      - "8081"
    depends_on:
      - eureka
    environment:
      SPRING_DATASOURCE_URL:
      EUREKA_HOST: eureka
    restart: always

  restaurant_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: restaurant
    container_name: restaurant
    expose:
      - "8082"
    depends_on:
      - eureka
    environment:
      SPRING_DATASOURCE_URL:
      EUREKA_HOST: eureka
    restart: always