server:
  port: 8081
spring:
  application:
    name: USER_SERVICE
  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URL}
  repositories:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST}