server:
  port: 8080

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
        - id: restaurant
          uri: lb://RESTAURANT
          predicates:
            - Path=/restaurant/**
        - id: eureka
          uri: lb://EUREKA
          predicates:
            - Path=/eureka/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST}