server:
  port: 8080

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/restaurant/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://eureka
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST}