version: '3.7'

services:

  database:
    image: mongo:latest
    restart: always
    container_name: database
    ports:
      - 27017:27017

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      KAFKA_CREATE_TOPICS: "authentication:1:1"
    depends_on:
      - zookeeper
