spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shubhamlatkar/foodgrid-config
          clone-on-start: false

server:
  port: 8888
